baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'New Blog'

paginate = 4

[params]
  description = "The fastest blog app"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"  
